### PR TITLE
Set task poller type for scalable task pollers

### LINKED ISSUE #2235: taskWorker.taskPollerType is not being set anywhere
## Expected Behavior

`pollerBalancer` balances `taskWorker.taskPollerType`

## Actual Behavior

`taskWorker.taskPollerType` is never set. Should be set to either Sticky or Not Sticky.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

### PR DESCRIPTION
**Pull request by kritibehl**
## What was changed

Updated `newScalableTaskPoller(...)` to accept and set `scalableTaskPoller.taskPollerType` and `serverSupportsAutoscaling`.

Wired poller types through when constructing scalable task pollers:

* `metrics.PollerTypeWorkflowTask` for mixed and non-sticky workflow task pollers
* `metrics.PollerTypeWorkflowStickyTask` for sticky workflow task pollers
* `metrics.PollerTypeActivityTask` for activity task pollers
* `metrics.PollerTypeNexusTask` for nexus task pollers
* `""` for local activity pollers (internal, not balanced)

Also restored `serverSupportsAutoscaling` threading through the constructor into `newPollScalerReportHandle`, fixed a formatting issue, and expanded test coverage with a table-driven test covering all poller types.

## Why?

`pollerBalancer` uses `scalableTaskPoller.taskPollerType` to register and balance poller types, but that field was never being set. This change wires the poller type through at construction time so balancing can operate on the intended poller types.

## Checklist

1. Closes #2235
2. How was this tested:
   * `go test ./internal -run Poller`
   * `go test ./...`
3. Any docs updates needed?
   * No docs updates needed.

### CODE REVIEW

File: internal/internal_nexus_worker.go [hunk 1]
```diff
@@ -50,8 +50,7 @@ func newNexusWorker(opts nexusWorkerOptions) (*nexusWorker, error) {
 			newScalableTaskPoller(
 				poller,
 				opts.executionParameters.Logger,
-				params.NexusTaskPollerBehavior,
-				params.serverSupportsAutoscaling),
+				params.NexusTaskPollerBehavior, ""),
```
Comment (Sushisource) [inline internal/internal_nexus_worker.go]: This should pass `PollerTypeNexusTask` it seems

File: internal/internal_worker.go [hunk 2]
```diff
@@ -545,7 +530,7 @@ func newActivityWorker(
 		slotSupplier:     slotSupplier,
 		maxTaskPerSecond: params.WorkerActivitiesPerSecond,
 		taskPollers: []scalableTaskPoller{
-			newScalableTaskPoller(poller, params.Logger, params.ActivityTaskPollerBehavior, params.serverSupportsAutoscaling),
+			newScalableTaskPoller(poller, params.Logger, params.ActivityTaskPollerBehavior, ""),
```
Comment (Sushisource) [inline internal/internal_worker.go]: And this `PollerTypeActivityTask`

File: internal/internal_worker_base.go [hunk 3]
```diff
@@ -888,20 +888,24 @@ func (ps *pollerSemaphore) updatePermits(maxPermits int) {
...
 	switch p := pollerBehavior.(type) {
 	case *pollerBehaviorAutoscaling:
 		tw.pollerCount = p.maximumNumberOfPollers
 		tw.pollerSemaphore = newPollerSemaphore(p.initialNumberOfPollers)
 		tw.pollerAutoscalerReportHandle = newPollScalerReportHandle(pollScalerReportHandleOptions{
-			initialPollerCount:        p.initialNumberOfPollers,
-			maxPollerCount:            p.maximumNumberOfPollers,
-			minPollerCount:            p.minimumNumberOfPollers,
-			logger:                    logger,
-			serverSupportsAutoscaling: serverSupportsAutoscaling,
```
Comment (yuandrew) [inline internal/internal_worker_base.go:905]: Why did we stop passing `serverSupportsAutoscaling` here? We still reference it in `newPollScalerReportHandle()`. I think this means autoscaling pollers can't sale down until they receive their first server scaling decision.

File: internal/internal_worker.go [hunk 4]
```diff
@@ -387,14 +387,13 @@ func newWorkflowTaskWorkerInternal(
 	// 2) local activity task poller will poll from laTunnel, and result will be pushed to laTunnel
 	localActivityTaskPoller := newLocalActivityPoller(laParams, laTunnel, interceptors, client, stopC)
 	localActivityWorker := newBaseWorker(baseWorkerOptions{
-		slotSupplier:     laParams.Tuner.GetLocalActivitySlotSupplier(),
-		maxTaskPerSecond: laParams.WorkerLocalActivitiesPerSecond,
+		slotSupplier: laParams.Tuner.GetLocalActivitySlotSupplier(), maxTaskPerSecond: laParams.WorkerLocalActivitiesPerSecond,
```
Comment (yuandrew) [inline internal/internal_worker.go]: These 2 lines got mashed into a single line, please separate them back into 2 lines

File: internal/internal_worker_base_test.go [hunk 5]
```diff
@@ -31,6 +31,23 @@ type (
 	}
 )
 
+func (s *ScalableTaskPollerSuite) TestNewScalableTaskPollerSetsTaskPollerType() {
```
Comment (yuandrew) [inline internal/internal_worker_base_test.go:34]: Can we also include a test that verifies each poller type matches the poller (i.e. sticky workflow poller actually gets `PollerTypeworkflowStickyTask`) for each type?

**Review by yuandrew — COMMENTED** [review]
Thanks for the contribution! Left a few comments

File: internal/internal_worker_base.go (hunk 3 above)
Comment (kritibehl) [reply internal/internal_worker_base.go:905]: Restored — it's now threaded through the constructor and into newPollScalerReportHandle.

File: internal/internal_worker.go (hunk 4 above)
Comment (kritibehl) [reply internal/internal_worker.go]: Fixed, split back onto separate lines.

File: internal/internal_worker_base_test.go (hunk 5 above)
Comment (kritibehl) [reply internal/internal_worker_base_test.go:34]: Added TestNewScalableTaskPollerAllTypes covering workflow, sticky, activity and nexus types.

File: internal/internal_nexus_worker.go (hunk 1 above)
Comment (kritibehl) [reply internal/internal_nexus_worker.go]: Fixed in the latest push.

File: internal/internal_worker.go (hunk 2 above)
Comment (kritibehl) [reply internal/internal_worker.go]: Fixed in the latest push.

**Comment by kritibehl** [comment]
Friendly follow-up, I addressed the review comments and updated the branch, including the missing poller types, restored `serverSupportsAutoscaling` and added broader poller-type test coverage.

Happy to rebase or make any other adjustments if helpful. Thanks again for the review.

**Review by yuandrew — APPROVED** [review]
Sorry for the delay, was on vacation for a few weeks. Thanks for the contribution!

**Comment by kritibehl** [comment]
Thanks for the review and approval!

I rebased onto latest main, resolved the conflicts, and reran go test ./... locally after the rebase: all passing.
