### PR TITLE
Fix GetWorkerStopChannel() for Local Activities

### LINKED ISSUE #1963: GetWorkerStopChannel no longer indicates worker shutdown for Local Activities
## Expected Behavior
`GetWorkerStopChannel()` should indicate that a worker has begun shutting down

## Actual Behavior
`GetWorkerStopChannel()` for local activities now indicates when the local activity specific stop channel has closed. This is due to https://github.com/temporalio/sdk-go/pull/1875.

The solution should be to also keep the worker stop channel in the Local Activity poller and have GetWorkerStopChannel() return that, while also ensuring shutdown behaves properly and the LA specific stop channel is closed at the right time.

Once this is fixed, see TODO comment linking this issue in integration tests and have Local Activity wait on that channel closure, instead of a manual time wait, to avoid potential race conditions

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

### PR DESCRIPTION
**Pull request by yuandrew**
## What was changed

Plumb WorkerStopChannel through for Local Activities

## Why?

Looks like this was never implemented to begin with

## Checklist

1. Closes #1963

2. How was this tested:

Changed a few tests to use this to avoid a race condition

3. Any docs updates needed?

### CODE REVIEW

File: test/integration_test.go [hunk 1]
```diff
@@ -2414,6 +2414,8 @@ func (ts *IntegrationTestSuite) TestGracefulLocalActivityCompletion() {
 	ctx, cancel := context.WithCancel(context.Background())
 	defer cancel()
 	localActivityFn := func(ctx context.Context) error {
+		// There is a slight delay between when workerStopChannel closes and when backgroundContextCancel is canceled
```
Comment (Quinn-With-Two-Ns) [inline test/integration_test.go]: Well the delay should be the graceful shutdown time no?

Comment (Quinn-With-Two-Ns) [reply test/integration_test.go]: `workerStopChannel` should be closed during graceful shutdown and then the context should be cancelled when the graceful period elapse or the shutdown finished

Comment (yuandrew) [reply test/integration_test.go]: hmm, looking at the graceful shutdown case, there is no delay.

but looking at `TestLocalActivityWorkerShutdownNoHeartbeat`, which I realized is non-graceful shutdown, we need a sleep. Otherwise, both LAs are able to complete before shutdown stops the LA.

Comment (Quinn-With-Two-Ns) [reply test/integration_test.go]: hm for graceful shutdown there should be a delay between the channel closing and the context closing. The context shouldn't close during the graceful shutdown period

Comment (yuandrew) [reply test/integration_test.go]: I was getting confused because the tests are doing different things. Added some comments to the tests to hopefully avoid any future confusion

For the non-graceful test, we want the LA to return `context canceled` err in order to test that we don't heartbeat on failure.

For the graceful tests, we want the LA to wait for shutdown to start before we complete, so when ctx is canceled doesn't matter in these tests

> The context shouldn't close during the graceful shutdown period

I've separately confirmed that this is true.
