### PR TITLE
Activity metrics should include task queue name

### LINKED ISSUE #449: Activity Latency Metrics Missing Task Queue Name
## Expected Behavior

Activity latency metrics like `activity_schedule_to_start_latency` and `activity_endtoend_latency` should be tagged with the task queue name like the Java SDK does.

## Actual Behavior

The activity latency metrics have `none` set for the task queue value.

## Steps to Reproduce the Problem

  1. Export prometheus metrics from an application running activity workers
  1. Search for the `activity_schedule_to_start_latency` metric and verify the task queue name is not set.

## Specifications

  - Version: v1.6.0
  - Platform: Linux

### PR DESCRIPTION
**Pull request by keelerm84**
Resolves #449 by tagging several activity related metrics with the task queue
name. This aligns more closely with the behavior of the Java SDK.

### CODE REVIEW

File: internal/internal_task_handlers.go [hunk 1]
```diff
@@ -1754,7 +1754,7 @@ func (ath *activityTaskHandlerImpl) Execute(taskQueue string, t *workflowservice
 
 	workflowType := t.WorkflowType.GetName()
 	activityType := t.ActivityType.GetName()
-	activityMetricsScope := metrics.GetMetricsScopeForActivity(ath.metricsScope, workflowType, activityType)
+	activityMetricsScope := metrics.GetMetricsScopeForRPC(ath.metricsScope, workflowType, activityType, taskQueue)
```
Comment (vitarb) [inline internal/internal_task_handlers.go:1757]: I think we should just update `GetMetricsScopeForActivity` to take additional parameter like in #452

Comment (keelerm84) [reply internal/internal_task_handlers.go:1757]: Well shoot. I would have liked to make those adjustments so I could have contributed here, but I guess we can just close this PR since you've done the work already. Thanks for resolving the issue.

Comment (vitarb) [reply internal/internal_task_handlers.go:1757]: Sorry, I've done before I've seen your PR, you can make adjustments here, no big deal. Let me cancel mine instead.

File: internal/common/metrics/utils.go [hunk 2]
```diff
@@ -79,9 +79,9 @@ func GetMetricsScopeForWorkflow(ts tally.Scope, workflowType string) tally.Scope
 }
 
 // GetMetricsScopeForRPC return properly tagged tally scope for workflow execution
-func GetMetricsScopeForRPC(ts tally.Scope, workflowType, activityType, taskqueueName string) tally.Scope {
+func GetMetricsScopeForRPC(ts tally.Scope, workflowType, activityType, taskQueueName string) tally.Scope {
```
Comment (keelerm84) [inline internal/common/metrics/utils.go:82]: Not directly related to this change, but I noticed the casing on this method was inconsistent with other places in the code so I made that minor tweak while I was in there.

File: internal/internal_task_handlers.go (hunk 1 above)
Comment (keelerm84) [reply internal/internal_task_handlers.go]: That's kind of you @vitarb. Thank you! I have so enjoyed working with temporal over the last several months and appreciate all the amazing work you have all done.

File: internal/common/metrics/utils.go (hunk 2 above)
Comment (vitarb) [reply internal/common/metrics/utils.go:82]: Great.

File: internal/internal_task_handlers.go (hunk 1 above)
Comment (vitarb) [reply internal/internal_task_handlers.go]: Thanks for your contribution to our community!

**Review by vitarb — APPROVED** [review]
LGTM
