### PR TITLE
Ensure WorkflowTaskExecutionFailureCounter is called with a tag

### LINKED ISSUE #1450: Metric `workflow_task_execution_failed` is used with different sets of labels causing errors with Prometheus
## Expected Behavior
Should not receive errors about metrics being registered incorrectly.

## Actual Behavior
Receiving a Prometheus error about the workflow_task_execution_failed metric being registered with different labels.

```
a previously registered descriptor with the same fully-qualified name as Desc{fqName: "temporal_workflow_task_execution_failed_total", help: "temporal_workflow_task_execution_failed_total counter", constLabels: {}, variableLabels: {app,client_name,namespace,environment,workflow_type,failure_reason,task_queue,worker_type,deployment,activity_type,env}} has different label names or a different help string
```

## Steps to Reproduce the Problem

I am still working on STR's (don't know how to break all the below with test code yet), but I can see that this metric is being used with different tags in different places.

#1295 added a tag here
https://github.com/temporalio/sdk-go/blob/69bc6c3a19cdb21d5252c3ad4a490109b9a2f39c/internal/internal_task_pollers.go#L421

But it is not being added in these uses of the metric.
https://github.com/temporalio/sdk-go/blob/69bc6c3a19cdb21d5252c3ad4a490109b9a2f39c/internal/internal_event_handlers.go#L1108
https://github.com/temporalio/sdk-go/blob/69bc6c3a19cdb21d5252c3ad4a490109b9a2f39c/internal/internal_event_handlers.go#L1298

And that will cause issues with Prometheus, as shown in this example.

```go
package main

import (
	"fmt"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/uber-go/tally/v4"
	tallyprom "github.com/uber-go/tally/v4/prometheus"

	"go.temporal.io/sdk/client"
	sdktally "go.temporal.io/sdk/contrib/tally"
)

func main() {
	metricsHandler := setupPrometheus()
	// These lines in any order will cause an error where the metrics have different labels
	metricsHandler.Counter("testing").Inc(1)
	metricsHandler.WithTags(map[string]string{"someName": "someValue"}).Counter("testing").Inc(1)
}

// Just setup stuff for Prometheus below here
var PrometheusSanitizeOptions = tally.SanitizeOptions{
	NameCharacters:       tally.ValidCharacters{Ranges: tally.AlphanumericRange, Characters: []rune{'_'}},
	KeyCharacters:        tally.ValidCharacters{Ranges: tally.AlphanumericRange, Characters: []rune{'_'}},
	ValueCharacters:      tally.ValidCharacters{Ranges: tally.AlphanumericRange, Characters: []rune{'_'}},
	ReplacementCharacter: tally.DefaultReplacementCharacter,
}

func setupPrometheus() client.MetricsHandler {
	cfg := tallyprom.Configuration{
		ListenAddress: "localhost:9090",
	}
	reporter, _ := cfg.NewReporter(tallyprom.ConfigurationOptions{
		Registry: prometheus.NewRegistry(),
		OnError: func(err error) {
			fmt.Printf("BOOM: %+v\n", err)
		},
	})
	scopeOpts := tally.ScopeOptions{CachedReporter: reporter, SanitizeOptions: &PrometheusSanitizeOptions}
	scope, _ := tally.NewRootScope(scopeOpts, time.Second)
	scope = sdktally.NewPrometheusNamingScope(scope)
	return sdktally.NewMetricsHandler(scope)
}
```

Which causes this error
```
a previously registered descriptor with the same fully-qualified name as Desc{fqName: "testing_total", help: "testing_total counter", constLabels: {}, variableLabels: {someName}} has different label names or a different help string
```

## Specifications

  - Version: sdk-go@v1.26.1

### PR DESCRIPTION
**Pull request by yuandrew**
## What was changed
Ensure the WorkflowTaskExecutionFailureCounter metric always has a tag set included.

## Why?

Prometheus returns an error when you try incrementing the same counter if one instance has a tag set and the other didn't.

I validated that Prometheus is okay with different tag sets (in this case if we happen to call one instance with `WorkflowError` and the other with `NonDeterminismError` tag sets). I'm not sure there's a scenario where we increment this counter from different sources, but if there is, this shouldn't be an issue with Prometheus.

## Checklist

1. Closes #1450

### CODE REVIEW

**Review by cretz — APPROVED** [review]

File: internal/internal_event_handlers.go [hunk 1]
```diff
@@ -1170,7 +1170,7 @@ func (weh *workflowExecutionEventHandlerImpl) ProcessEvent(
 	}
 	defer func() {
 		if p := recover(); p != nil {
-			weh.metricsHandler.Counter(metrics.WorkflowTaskExecutionFailureCounter).Inc(1)
+			incrementWorkflowTaskFailureCounter(weh.metricsHandler, "NonDeterminismError")
```
Comment (Quinn-With-Two-Ns) [inline internal/internal_event_handlers.go:1173]: I don't think the panics here are always caused just by non determinism, what is users workflow code panics because of a code bug?

Comment (Quinn-With-Two-Ns) [reply internal/internal_event_handlers.go:1173]: Also I am pretty sure we can still end up emitting emitting this metric twice , that should be addressed to close https://github.com/temporalio/sdk-go/issues/1450

Comment (yuandrew) [reply internal/internal_event_handlers.go:1173]: > I don't think the panics here are always caused just by non determinism, what is users workflow code panics because of a code bug?

From my testing, when a user's workflow code panics, we trigger the call in `internal_task_pollers.go`. The only way I saw us recover a panic from the defer call is when we `panicIllegalState` from the state machine. But to be safe, I can add a check to check the panic message for `TMPRL1100` to use `NonDeterminismError` and default to `WorkflowError` for all other scenarios.

> Also I am pretty sure we can still end up emitting emitting this metric twice , that should be addressed to close https://github.com/temporalio/sdk-go/issues/1450

Do you have any idea what scenario could cause this double logging? I've tried to hit this scenario the last few days and haven't been able to come up with anything. 

The issue itself is on Prometheus erroring out due to the metric being emitted twice, once due to having a tag and the other without, which is now resolved with this PR (calling with different logs doesn't cause Prometheus to throw an error). But I'm happy to address this double logging, I'm just not able to find a scenario where we double log.

Comment (Quinn-With-Two-Ns) [reply internal/internal_event_handlers.go:1173]: Sure let me try to come up with a counter example

Comment (yuandrew) [reply internal/internal_event_handlers.go:1173]: I got a scenario that hits both `ProcessEvent` and `RespondTaskCompletedWithMetrics`. It looks like when both of these functions emit this metric, only the `RespondTaskCompletedWithMetrics` inc gets counted. 

A few scenarios I ran:
1. When `RespondTaskCompletedWithMetrics` is the only one emitting the metric, the count is 1
2. When `ProcessEvent` is the only one emitting the metric, the count is 0
3. When neither emit the metric, the metric doesn't get emitted to http://localhost:9090/metrics altogether.

Is there some kind of scoping or something that's causing the earlier `ProcessEvent` metric to get reset? I'm using the metrics sample to emit metrics to localhost://9090/metrics https://github.com/yuandrew/playground/tree/duplicate_logging
