### PR TITLE
Bounds check stack trace line indexes

### LINKED ISSUE #624: unhandled panic from workflow code
Panic from workflow code, including any code running in corotine created by any workflow.Go() should be handled by sdk.
User reported this panic stack trace suggest that we might have panic coming from [here](https://github.com/temporalio/sdk-go/blob/384e906eaace5e8914a6c0890419c23eba3b033c/internal/internal_workflow.go#L863)
panic: manual inject panic from go routine [recovered]
	panic: runtime error: slice bounds out of range [9:8]

goroutine 52489 [running]:
go.temporal.io/sdk/internal.getStackTraceRaw({0xc000e7c180, 0x14}, 0x9, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:863 +0x1bd
go.temporal.io/sdk/internal.getStackTrace({0x52ba998, 0x7f069a39aa68}, {0x30317d5, 0x5}, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:853 +0xab
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1.1()
	external/io_temporal_go_sdk/internal/internal_workflow.go:936 +0x73
panic({0x2995340, 0x346e360})
	GOROOT/src/runtime/panic.go:1038 +0x215
xxxxxxx/xxxx/xxxxxxxx.(*Workflow).startBlocks.func1({0xc001857950, 0x1})
	xxxxx/xxxxxxxx/workflow.go:432 +0x27
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1(0xc0008ee120)
	external/io_temporal_go_sdk/internal/internal_workflow.go:941 +0xde
created by go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine
	external/io_temporal_go_sdk/internal/internal_workflow.go:932 +0x365
panic: manual inject panic from go routine [recovered]
	panic: runtime error: slice bounds out of range [9:8]

goroutine 52382 [running]:
go.temporal.io/sdk/internal.getStackTraceRaw({0xc001e65698, 0x14}, 0x9, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:863 +0x1bd
go.temporal.io/sdk/internal.getStackTrace({0x52ba998, 0x34ed810}, {0x30317d5, 0x5}, 0x4)
	external/io_temporal_go_sdk/internal/internal_workflow.go:853 +0xab
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1.1()
	external/io_temporal_go_sdk/internal/internal_workflow.go:936 +0x73
panic({0x2995340, 0x346e360})
	GOROOT/src/runtime/panic.go:1038 +0x215
xxxxxxx/xxxxxxx/xxxxxxxxxx.(*Workflow).startBlocks.func1({0xc001c8fe50, 0x1})
	xxxxxxx/xxxxxxxxxx/workflow.go:432 +0x27
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1(0xc0024b1030)
	external/io_temporal_go_sdk/internal/internal_workflow.go:941 +0xde
created by go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine
	external/io_temporal_go_sdk/internal/internal_workflow.go:932 +0x365

### PR DESCRIPTION
**Pull request by cretz**
## What was changed

A bounds check was done to make sure the start is not after the end when trimming stack indexes.

## Why?

In #624, a panic trace showed that the start passed the end. Despite all attempts to replicate I have not, so we just make sure to limit the bounds.

## Checklist

1. Closes #624

### CODE REVIEW

File: internal/internal_workflow.go [hunk 1]
```diff
@@ -860,7 +860,12 @@ func getStackTraceRaw(top string, omitTop, omitBottom int) string {
 		return rawStack
 	}
 	lines := strings.Split(rawStack, "\n")
-	lines = lines[omitTop : len(lines)-omitBottom]
+	// If the top is after the end, set as same
+	omitEnd := len(lines) - omitBottom
+	if omitTop > omitEnd {
+		omitTop = omitEnd
```
Comment (yiminc) [inline internal/internal_workflow.go:866]: I would rather not omit in this case, so we have a chance to see the full stack trace, what do you think?

Comment (cretz) [reply internal/internal_workflow.go:866]: That can work. This really shouldn't happen ever anyways, so I am a bit disappointed that we're having to decide how to handle the invalid index when it does. But unfortunately without the ability to easily replicate, I can never know I fixed it otherwise.

I will make the change.

Comment (cretz) [reply internal/internal_workflow.go]: Done.

**Review by yiminc — APPROVED** [review]

**Review by Sushisource — APPROVED** [review]
