### PR TITLE
Health check retry

### LINKED ISSUE #438: Client creation doesn't have any retries if health check intermittently fails
Health check code:

```
func checkHealth(connection grpc.ClientConnInterface, options ConnectionOptions) error {
	if options.DisableHealthCheck {
		return nil
	}
	healthClient := healthpb.NewHealthClient(connection)
	request := &healthpb.HealthCheckRequest{
		Service: healthCheckServiceName,
	}
	healthCheckTimeout := options.HealthCheckTimeout
	if healthCheckTimeout == 0 {
		healthCheckTimeout = defaultHealthCheckTimeout
	}
	ctx, cancel := context.WithTimeout(context.Background(), healthCheckTimeout)
	defer cancel()
	resp, err := healthClient.Check(ctx, request)
	if err != nil {
		return fmt.Errorf("health check error: %w", err)
	}
	if resp.Status != healthpb.HealthCheckResponse_SERVING {
		return fmt.Errorf("health check returned unhealthy status: %v", resp.Status)
	}
	return nil
}
```

User's only option is to disable the health check or add retries on their application layer. For checkHealth calls on create client, we may want more sophisticated logic, or at least the ability to configure something via ConnectionOptions

### PR DESCRIPTION
**Pull request by vitarb**
Resolves #438 by adding configurable healthcheck timeout for the client.
Default value is set to 10 seconds, which means that now client creation would block sending health check requests in case if server is not available.

### CODE REVIEW

File: internal/client.go [hunk 1]
```diff
@@ -423,6 +425,10 @@ type (
 		// Default: 5s.
 		HealthCheckTimeout time.Duration
 
+		// HealthCheckRetryFor defines maximum amount of time that health check should be retried for.
+		// Defaults to 10s, once this timeout is reached error will be propagated to the client.
+		HealthCheckRetryFor time.Duration
```
Comment (mastermanu) [inline internal/client.go:430]: [Nit] I think we need better name here. OR, HealthCheckTimeout should represent the overall time including all attempts, and we have the new field specify the PerAttempt timeout (or have that hard-coded). I can see how this might cause some weirdness with breaking changes though...

**Review by mastermanu — APPROVED** [review]

File: internal/client.go (hunk 1 above)
Comment (vitarb) [reply internal/client.go:430]: We can slightly turn it and add `HealthCheckAttemptTimeout`, which would allow us to use `HealthCheckTimeout` as an aggregate one, what do you think?

**Review by mfateev — APPROVED** [review]
