### PR TITLE
Don't heartbeat local activity on non-graceful worker shutdown

### LINKED ISSUE #1706: ProcessWorkflowTask is not stopped on worker.Stop()
## Expected Behavior
`ProcessWorkflowTask` should stop

## Actual Behavior
A WorkflowTask started by a stopped worker continues to send heartbeats, blocking further workflow execution.

## Steps to Reproduce the Problem

The following code is based on the server's per-namespace worker [implementation](https://github.com/temporalio/temporal/blob/main/service/worker/pernamespaceworker.go). It starts the worker, stops it, and then starts it again using the same client.

The workflow executes a series of local activities, similar to the server's Scheduler workflow.

If the worker is stopped during the execution of a local activity, we will see a "canceled" error in the logs:
```
2024/11/08 10:15:49 ERROR Activity failed
```

However, this error is ignored by the workflow, which will continue processing the current WorkflowTask and will schedule another local activity. This activity will not be executed since the worker is stopped. `ProcessWorkflowTask` will remain active, though, and will keep sending heartbeats until either a network timeout occurs or the history size limit is reached.

Heartbeats can be seen in the logs:
```
2024/11/08 10:16:28 DEBUG Force RespondWorkflowTaskCompleted
```

```go
package main

import (
	"context"
	"fmt"
	"time"

	"go.temporal.io/api/enums/v1"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

const (
	hostPort   = "localhost:7233"
	namespace  = "default"
	taskQueue  = "default"
	workflowID = "test-workflow"

	sleepDuration = 100 * time.Millisecond
	nActivities   = 10
)

type Worker struct {
	parentClient client.Client
	client       client.Client
	worker       worker.Worker
}

func NewWorker(c client.Client) *Worker {
	return &Worker{parentClient: c}
}

func (w *Worker) Start() error {
	c, err := newTemporalClientFromExisting(w.parentClient)
	if err != nil {
		return fmt.Errorf("create client: %w", err)
	}
	tw := newTemporalWorker(c)
	err = tw.Start()
	if err != nil {
		return fmt.Errorf("start worker: %w", err)
	}
	w.client = c
	w.worker = tw
	return nil
}

func (w *Worker) Stop() {
	w.worker.Stop()
	w.client.Close()
}

func newTemporalClient() (client.Client, error) {
	return client.Dial(client.Options{
		HostPort:  hostPort,
		Namespace: namespace,
	})
}

func newTemporalClientFromExisting(c client.Client) (client.Client, error) {
	return client.NewClientFromExisting(c, client.Options{})
}

func newTemporalWorker(c client.Client) worker.Worker {
	w := worker.New(c, taskQueue, worker.Options{})
	w.RegisterWorkflow(Workflow)
	w.RegisterActivity(Activity)
	return w
}

func Workflow(ctx workflow.Context) error {
	for {
		for range nActivities {
			ctx := workflow.WithLocalActivityOptions(ctx, workflow.LocalActivityOptions{
				StartToCloseTimeout: time.Minute,
			})
			err := workflow.ExecuteLocalActivity(ctx, Activity).Get(ctx, nil)
			if err != nil {
				workflow.GetLogger(ctx).Error("Activity failed.", "Error", err)
			}
		}
		workflow.Sleep(ctx, sleepDuration)
		if workflow.GetInfo(ctx).GetContinueAsNewSuggested() {
			return workflow.NewContinueAsNewError(ctx, Workflow)
		}
	}
}

func Activity(ctx context.Context) error {
	time.Sleep(sleepDuration)
	return ctx.Err()
}

func startWorkflow(ctx context.Context, c client.Client) error {
	opts := client.StartWorkflowOptions{
		ID:                    workflowID,
		TaskQueue:             taskQueue,
		WorkflowIDReusePolicy: enums.WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING,
	}
	_, err := c.ExecuteWorkflow(ctx, opts, Workflow)
	return err
}

func main() {
	ctx := context.Background()
	c, err := newTemporalClient()
	if err != nil {
		fmt.Printf("Error creating client: %v\n", err)
	}

	err = startWorkflow(ctx, c)
	if err != nil {
		fmt.Printf("Error starting workflow: %v\n", err)
		return
	}
	fmt.Println("Workflow started.")

	w := NewWorker(c)
	for {
		err = w.Start()
		if err != nil {
			fmt.Println("Error starting worker:", err)
			return
		}
		time.Sleep(33 * sleepDuration)
		w.Stop()
	}
}
```

## Specifications

  - Version:
  - Platform:

### PR DESCRIPTION
**Pull request by yuandrew**
## What was changed

Stop local activity from heartbeating after worker has shutdown

## Why?

They shouldn't heartbeat after they've been canceled due to non-graceful shutdown

## Checklist

1. Closes #1706 

2. How was this tested:

added integration test

3. Any docs updates needed?

### CODE REVIEW

File: internal/internal_task_handlers.go [hunk 1]
```diff
@@ -998,6 +998,17 @@ processWorkflowLoop:
...
+						// to avoid heartbeating after local activity is no longer being run
+						var appErr *ApplicationError
+						if errors.As(lar.err, &appErr) {
+							// AppErr with ErrCanceled errType are non-server initiated cancellations.
+							if appErr.errType == ErrCanceled.Error() {
+								break processWorkflowLoop
+							}
+						}
+
 						response, err = workflowContext.ProcessLocalActivityResult(workflowTask, lar)
```
Comment (cretz) [inline internal/internal_task_handlers.go:1012]: I need some help understanding the issue. Why don't we want the workflow to heartbeat until the local activity has completed? Can you help me understand what logic below without this new change was causing `ProcessLocalActivityResult` to return both a nil `response` and `err` causing us to continue to wait for local activity? Wouldn't the `retryLocalActivity` be false since this is a canceled error and therefore `err` be non-nil?

Comment (yuandrew) [reply internal/internal_task_handlers.go:1012]: `retryLocalActivity` is false, but `w.hasPendingLocalActivityWork()` in `CompleteWorkflowTask` is true, causing `response` and `err` to be nil and to loop back

Comment (cretz) [reply internal/internal_task_handlers.go:1012]: Why is `hasPendingLocalActivityWork` still true when the local activity is done? Hrmm, what if `hasPendingLocalActivityWork` _is_ legitimately true because another local activity is still pending. My concern now is what if I have two local activities running and only one has responded with cancel and the other is still processing its cleanup logic? This breaks out of the whole loop even though another local activity may finish with success. I wonder if we should just consider _this_ local activity as no longer pending.

I am now generally curious about concurrent local activities with one failing with the cancel and one succeeding what would be recorded in the workflow task? What if the success came before the cancel one but both before any heartbeat occurred, does that mean only the one success marker is captured? Is that safe? (sorry, my heading is getting a bit lost thinking about it).

File: internal/internal_task_handlers.go [hunk 2]
```diff
@@ -998,6 +998,17 @@ processWorkflowLoop:
 
 					case lar := <-workflowTask.laResultCh:
 						// local activity result ready
+
+						// When local activity is canceled due to non-server cancel, we break loop here
+						// to avoid heartbeating after local activity is no longer being run
+						var appErr *ApplicationError
+						if errors.As(lar.err, &appErr) {
+							// AppErr with ErrCanceled errType are non-server initiated cancellations.
+							if appErr.errType == ErrCanceled.Error() {
```
Comment (Quinn-With-Two-Ns) [inline internal/internal_task_handlers.go:1007]: A user can return this error to no? and a user doesn't have to return this error when the local activity worker is shut down so I am not sure this is the correct way to detect this condition.

Comment (yuandrew) [reply internal/internal_task_handlers.go:1007]: Do you think it's a viable fix to somehow pass a custom error through `laResultCh` altogether? That seems like the easiest way to communicate that the worker has shutdown and we can stop processing this WFT

> a user doesn't have to return this error when the local activity worker is shut down
My understanding is when worker shuts down, it cancels context and the user's code just stops running. Are you saying the user can handle that context cancellation and return their own custom error?

Comment (yuandrew) [reply internal/internal_task_handlers.go:1007]: > shutdown comes from the top down to both workers

I don't think it does in this scenario. If I don't return to `laResultCh`, the `heartbeatTimer.C` keeps firing and the test continues to run for the full 15 seconds.

Comment (yuandrew) [reply internal/internal_task_handlers.go:1007]: oh actually, I can probably use `workflowContext.laTunnel.stopCh`

File: internal/internal_task_handlers.go (hunk 1 above)
Comment (yuandrew) [reply internal/internal_task_handlers.go:1012]: Do multiple local activities matter if the worker is shutting down? Isn't it all moot, unless the WFT happens to finish as the worker shuts down?

File: internal/internal_task_handlers.go [hunk 3]
```diff
@@ -939,17 +939,24 @@ processWorkflowLoop:
...
-							workflowContext.CompleteWorkflowTask(workflowTask, false),
-							startTime,
-						)
-						if err != nil {
-							errRet = &workflowTaskHeartbeatError{Message: fmt.Sprintf("error sending workflow task heartbeat %v", err)}
-							return
-						}
-						if workflowTask == nil {
+						select {
+						case <-workflowContext.laTunnel.stopCh:
```
Comment (Quinn-With-Two-Ns) [inline internal/internal_task_handlers.go:943]: Doesn't this channel close when the worker is shutting down during graceful shutdown? What happens when a local activity competes during graceful shutdown? Will the result be ignored?

Comment (yuandrew) [reply internal/internal_task_handlers.go:943]: no, this channel should now only close after local activities finish running, from https://github.com/temporalio/sdk-go/pull/1875.
```
    // We want a separate stop channel for local activities because when a worker shuts down,
	// we need to allow pending local activities to finish running for that workflow task.
	// After all pending local activities are handled, we then close the local activity stop channel.
	laStopChannel := make(chan struct{})
	laParams := params
	laParams.WorkerStopChannel = laStopChannel

	// laTunnel is the glue that hookup 3 parts
	laTunnel := newLocalActivityTunnel(getReadOnlyChannel(laStopChannel))
```

Also added another integration test validating this behavior

File: test/integration_test.go [hunk 4]
```diff
@@ -7707,3 +7708,141 @@ func (ts *IntegrationTestSuite) TestLocalActivityFailureMetric_BenignHandling()
 	// Expect count to remain unchanged
 	ts.assertMetricCount(metrics.LocalActivityExecutionFailedCounter, currCount)
 }
+
+func (ts *IntegrationTestSuite) TestLocalActivityWorkerShutdownNoHeartbeat() {
+	// FYI, setup of this test allows the worker to wait to stop for 10 seconds
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	localActivityFn := func(ctx context.Context) error {
+		time.Sleep(300 * time.Millisecond)
```
Comment (Quinn-With-Two-Ns) [inline test/integration_test.go:7717]: nit: can we use the worker shutdown channel here to avoid any potential timing race? Basically complete after the shutdown channel is closed so we know the activity completed after the worker was requested to shutdown

Comment (yuandrew) [reply test/integration_test.go:7717]: looks like because of https://github.com/temporalio/sdk-go/pull/1875, now the LA worker stop channel is `ww.localActivityStopC`, which only closes after pending LAs are complete. 

I can work on a separate PR to see if I can fix `GetWorkerStopChannel` to return the worker shutdown channel instead of the LA shutdown channel, and in that PR switch these and some prev tests i wrote to use GetWorkerStopChannel instead of a manual wait

Comment (Quinn-With-Two-Ns) [reply test/integration_test.go:7717]: Can you open up an issue for this and add a TODO here? We will see if we can pull it in next sprint.

File: internal/internal_task_handlers.go (hunk 3 above)
Comment (Quinn-With-Two-Ns) [reply internal/internal_task_handlers.go:943]: Talked offline this should be fine, maybe just add a comment explaining what is happening here for future readers.

**Review by Quinn-With-Two-Ns — APPROVED** [review]

**Review by cretz — COMMENTED** [review]
Btw, no need to wait for my review/approval as this is a bit too deep for me to dig back into, @Quinn-With-Two-Ns's review is enough IMO
